### ISSUE TITLE
Add New Model

### ISSUE THREAD

**Issue by zacharysarette** [lunarcloud/gameinputjs#14]
new gi.Model(
	gi.Type.Plumber,
	"nintendo-generic",
	"USB,2-axis 8-button gamepad   (STANDARD GAMEPAD Vendor: 0583 Product: 2060)",
	"macOS",
	new gi.Schema.GamePadAPI(
		/* d_up */  13,
		/* d_down */  14,
		/* d_left */  15,
		/* d_right */  16,
		/* menu */  10,
		/* button0 */  1,
		/* button1 */  2,
		/* button2 */  3,
		/* button3 */  4,
		/* l_up */  undefined,
		/* l_down */  undefined,
		/* l_left */  undefined,
		/* l_right */  undefined,
		/* r_up */  new gi.Schema.AxisButton(-4),
		/* r_down */  new gi.Schema.AxisButton(4),
		/* r_left */  new gi.Schema.AxisButton(-3),
		/* r_right */  new gi.Schema.AxisButton(3),
		/* l_button */  5,
		/* r_button */  6,
		/* l_trigger */  undefined,
		/* r_trigger */  undefined
	)
),

**Comment by lunarcloud** [comment]
Added
