### ISSUE TITLE
Add Model/ Numbered Generic

### ISSUE THREAD

**Issue by zacharysarette** [lunarcloud/gameinputjs#16]
new gi.Model(
	gi.Type.Hedgehog,
	"generic",
	"USB  Joystick (Vendor: 1345 Product: 1030)",
	"macOS",
	new gi.Schema.GamePadAPI(
		/* d_up */  new gi.Schema.AxisButton(-2),
		/* d_down */  new gi.Schema.AxisButton(2),
		/* d_left */  new gi.Schema.AxisButton(-1),
		/* d_right */  new gi.Schema.AxisButton(1),
		/* menu */  10,
		/* button0 */  1,
		/* button1 */  2,
		/* button2 */  3,
		/* button3 */  4,
		/* l_up */  undefined,
		/* l_down */  undefined,
		/* l_left */  undefined,
		/* l_right */  undefined,
		/* r_up */  new gi.Schema.AxisButton(-4),
		/* r_down */  new gi.Schema.AxisButton(4),
		/* r_left */  new gi.Schema.AxisButton(-3),
		/* r_right */  new gi.Schema.AxisButton(3),
		/* l_button */  5,
		/* r_button */  6,
		/* l_trigger */  7,
		/* r_trigger */  8
	)
),

![dsc_0210](https://cloud.githubusercontent.com/assets/650130/24086586/75b2604a-0d55-11e7-8912-72b78926758f.jpeg)
![dsc_0211](https://cloud.githubusercontent.com/assets/650130/24086588/75b2e772-0d55-11e7-9280-0f85df83346d.jpeg)
![dsc_0212](https://cloud.githubusercontent.com/assets/650130/24086587/75b272ce-0d55-11e7-8a3c-a5c309638241.jpeg)

**Comment by lunarcloud** [comment]
Added, need to fix the button text to be numbers instead of Hedgehog
